### ISSUE TITLE
Allow for dedicated configuration file in the `.github/` directory

### ISSUE THREAD

**Issue by pradyunsg** [sanitizers/chronographer-github-app#20]
https://github.com/pypa/pip/tree/229981192d56d4bd4f1750589097fd0d0b098d64/.github

As of today, pip's `.github` directory contains a bunch of `<botname>.yml` files for configuration of the GitHub Bots that we're using. It'd be nice to have a `chronographer.yml` file in sync with that instead of a `config.yml` file.

**Comment by webknjaz** [comment]
Do you think we should support both? `<botname>.yml` with a fallback to `config.yml`? Should we merge settings if set in both?

I think I picked up this `config.yml` thing from https://github.com/KengoTODA/rtd-bot/ but I probably saw it elsewhere. Maybe it even was being promoted by Probot at some point.

**Comment by webknjaz** [comment]
Looks like a holywarish topic tho. It feels like there's two camps in the Python community: ones who want to put all the configs in one file and others who don't. (Also known as putting flake8+pylint+tox into setup.cfg vs their own configs :smiley:)

**Comment by pradyunsg** [comment]
> Do you think we should support both?

I think that'd be reasonable.

> Should we merge settings if set in both?

Fail if you see both -- "choose a camp". :P

**Comment by webknjaz** [comment]
> Fail if you see both -- "choose a camp". :P

Now I think that I would rather not waste another HTTP call if the first config is there. Just check `<botname>.yml` and only if it's missing also download `config.yml`.

**Comment by webknjaz** [comment]
I've done some thinking and supporting a fallback is waste of an HTTP call to (hence is bad for the API rate limit). I'll keep the fallback for now and attempt to track down all the App installs to replace the config locations.
