### ISSUE TITLE
opt-out the tagging by bot:chronographer:provided 

### ISSUE THREAD

**Issue by praiskup** [sanitizers/chronographer-github-app#40]
This tag is not needed in our case - it is enough to see a failed CI check mark.

It would be nice to have an option to turn off tagging.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sanitizers) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sanitizers/chronographer-github-app/issues/40">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sanitizers/chronographer-github-app/issues/40/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sanitizers/chronographer-github-app/issues/40/pledge.svg">
</picture>
</a>

**Comment by webknjaz** [comment]
Ref #12

**Comment by webknjaz** [comment]
Sounds reasonable. We'd need to decide the shape/UX of the config for this, though. Perhaps
```yaml
labels:
  changelog-detected: change note found  # default: `bot:chronographer:provided`, disable with `~`
```
would do. `~` is an equivalent of `None` / `null` in YAML, IIRC. Needs checking, though.

If somebody wants to make a PR, here's the places where this would need to be integrated:
- https://github.com/sanitizers/chronographer-github-app/blob/5509edb/chronographer/event_handlers.py#L296C5-L296C29
- https://github.com/sanitizers/chronographer-github-app/blob/5509edb/chronographer/event_handlers.py#L303C21-L303C35

And the config-related examples are here:
- https://github.com/sanitizers/chronographer-github-app/blob/5509edb/chronographer/event_handlers.py#L155C23-L155C70
- https://github.com/sanitizers/chronographer-github-app/blob/5509edb/chronographer/event_handlers.py#L162C5-L162C36

Make sure to follow the existing code style around, I don't remember if I configured many linters.

**Comment by webknjaz** [comment]
@praiskup I've gone for the following UX:
```yaml
labels:
  fragment-provided: ~  # opt out
```

The feature is live. Give it a try.

**Comment by praiskup** [comment]
And it worked in https://github.com/rpm-software-management/mock/pull/1393 !
