### ISSUE TITLE
Skip-label configuration seems broken

### ISSUE THREAD

**Issue by praiskup** [sanitizers/chronographer-github-app#41]
I'm trying to pick a different "skip label":

```
$ cat .github/chronographer.yml 
---
# Config for https://github.com/sanitizers/chronographer-github-app
labels:
  skip-changelog: no-release-notes
```

but the configuration doesn't seem to work:
https://github.com/rpm-software-management/mock/pull/1438

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sanitizers) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sanitizers/chronographer-github-app/issues/41">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sanitizers/chronographer-github-app/issues/41/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sanitizers/chronographer-github-app/issues/41/pledge.svg">
</picture>
</a>

**Comment by webknjaz** [comment]
@praiskup you have to merge the config in. The ones coming from PRs are untrusted. The bot gets the config from the default branch.

**Comment by webknjaz** [comment]
@praiskup can we close this or do you have any other suggestions?

**Comment by praiskup** [comment]
yes, sorry for the noise
