### ISSUE TITLE
[TODO] Allow enforcing custom suffices

### ISSUE THREAD

**Issue by webknjaz** [sanitizers/chronographer-github-app#7]
Like `.rst` ending

**Comment by pradyunsg** [comment]
Or like towncrier ones?

**Comment by webknjaz** [comment]
That's already enforced. Apparently, you can add random stuff after fragment types and it'll work

**Comment by webknjaz** [comment]
@pradyunsg see https://github.com/sanitizers/chronographer-github-app/blob/master/chronographer/event_handlers.py

**Comment by pradyunsg** [comment]
Oh that's cool!

**Comment by webknjaz** [comment]
I just need to add config support so that it could be set per repo.
