### ISSUE TITLE
[TODO] Address the edge case of the changelog generation commit/PR

### ISSUE THREAD

**Issue by webknjaz** [sanitizers/chronographer-github-app#8]
I think that when there's a "release" PR, we should report a `neutral` outcome with an explanation that changelog fragments are being replaced by a change in the target changelog file which is normal.

Ref: https://github.com/tox-dev/tox/issues/1291#issuecomment-507680582
Ref: https://github.com/tox-dev/tox/pull/1362#issuecomment-507677428

**Comment by webknjaz** [comment]
cc @gaborbernat @asottile

**Comment by gaborbernat** [comment]
Yes yes 😁
